### ISSUE TITLE
Help with Ace Toggle

### ISSUE THREAD

**Issue by anastasiaalt** [anastasiaalt/blackjack#1]
See last commit for Javascript lines 239 to 273; this deals with the toggling the ace between 11 and 1 depending on the hand value

The logic I have definitely works but syntax of function not working. I eventually will put this into some kind of loop but for now I want to test in slightly repetitive way I have written

I cannot get the colans and the structure of all the if/else statements to work to get the logic I am testing across. Please help!

**Comment by sungchoi** [comment]
Hi Anastasia,

Can you be more specific? What is the error you are getting? What line number is it pointing you to?

**Comment by anastasiaalt** [comment]
It's a syntax error, I am not able to identify where it is that I have too many or too few } and ; in the code

**Comment by anastasiaalt** [comment]
I was just able to fix it! Thanks, will submit another issue now to piece together my challenge here

**Comment by sungchoi** [comment]
Good job debugging. I knew you could do it!
